#!/bin/sh

FILE="/usr/share/luci/menu.d/luci-mod-system.json"

if [ -f "$FILE" ]; then
    # Tworzymy kopię zapasową pliku
    cp "$FILE" "${FILE}.bak"

    # Usuwamy linię z kluczem, kolejne 10 linii bloku oraz 1 pustą linię pod spodem (+11 linii łącznie)
    sed -i '/"admin\/system\/plugins": {/,+11d' "$FILE"
    # Czyszczenie pamięci podręcznej LuCI
    rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
fi
# Ustawienie +x dla 20_cpu_temperature
chmod +x /etc/sysinfo.d/20_cpu_temperature
# Usuwanie repo 'obsy' i 'nss' z distfeeds.list -> powodują błędy dla 'apk update'
sed -i '/obsy/d' /etc/apk/repositories.d/distfeeds.list
sed -i '/nss/d' /etc/apk/repositories.d/distfeeds.list
# Ustawienie +x dla skryptu nss_thermal
chmod +x /usr/libexec/rpcd/nss_thermal
exit 0
