#!/bin/sh
T=""
F=/sys/class/thermal/thermal_zone0
for f in $F; do
    [ -e $f ] || continue
    [ -e $f/temp ] && NAME=$(cat $f/temp)
		for i in $f/temp; do
		    [ -n "$T" ] && T="$T, "
		    T="$T"$(awk '{if ($1 == 0){printf ""}else{printf "%.2f C", $1/1000}}' $i 2>/dev/null)
		done
done
[ -n "$T" ] && echo "CPU temp: $T"
exit 0
